server:
  port: 9005

  eureka:
    client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  spring:
    application:
    name: springcloud-config
      cloud:
    config:
      server:
      git:
        uri: https://github.com/lion82-wxx/1904b.git
        search-paths: /
        username:
        password:
